name: CI
on: [push, pull_request]
jobs:
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22.x' }
      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: 'stable' }
      - run: flutter pub get
        working-directory: client
      - run: flutter analyze
        working-directory: client
